### ISSUE TITLE
Fix fetch error on netlify

### ISSUE THREAD

**Issue by breadadams** [microlinkhq/react-microlink#8]
![img_9878](https://user-images.githubusercontent.com/5795227/33519932-1a5a591a-d7b1-11e7-9d07-42adfb7f0a94.PNG)

**Comment by breadadams** [comment]
https://github.com/github/fetch

**Comment by Kikobeats** [comment]
Hmm I prefer don't add polyfills with the library, but, if it necessary, this will be a better solution:
https://github.com/developit/unfetch

**Comment by breadadams** [comment]
Good point
